### ISSUE TITLE
Console not working?

### ISSUE THREAD

**Issue by qohelet** [Sova777/PerlInNetBeans#1]
Starting a Perl-Script from the IDE works fine, but the console doesn't work.
I can't give keyboard-inputs or end the program with CTRL+C

**Comment by Sova777** [comment]
Yes. Some years ago I found tutorial with this limitation. On weekend I will research this question again.

**Comment by Sova777** [comment]
Can you try this commit:?https://github.com/Sova777/PerlInNetBeans/commit/b7acfafbfa6b148a639e8012b9dfde3d1b9e1222
Also I can create nbm file.

**Comment by Sova777** [comment]
Better to use this sample in order to check fix:

#!/usr/bin/perl
$| = 1;

for (my $i = 0; $i < 10; $i++) {
  print "Hello!\n";
  sleep(1);
}
print "Type any message:";
$A=<STDIN>;
chop $A;
print "***$A***";

**Comment by qohelet** [comment]
Would be nice if you could create a nbm file. Thank you

**Comment by Sova777** [comment]
I uploaded nbm file to http://plugins.netbeans.org/plugin/10668/perl ('NetBeans 8.2 or NetBeans 8.1 tab)

**Comment by qohelet** [comment]
Well done! The console works now.
But apparently the Code-Formatting and Syntax highlighting is messed up now :(
